services:
  cpp-dev:
    build: ./setup
    image: cpp-course:latest
    container_name: csci330_f25-cpp-dev
    platform: linux/amd64
    volumes:
      - .:/home/student/workspace
    working_dir: /home/student/workspace
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
    command: /bin/bash